## Importing libraries:

In [1]:
import numpy as np
import pandas as pd

## OneHotEncoding:

In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# 1. Indoor Object Detection Dataset Setup
data = {
    'Room_Type': ['Kitchen', 'Bedroom', 'Living Room', 'Kitchen', 'Bedroom'], # Nominal
    'Object_Color': ['Red', 'Blue', 'Green', 'Red', 'Blue'],                  # Nominal
    'Object_Size': ['Small', 'Large', 'Medium', 'Medium', 'Small'],           # Ordinal
    'Target_Object': ['Cup', 'Bed', 'Sofa', 'Plate', 'Chair']                 # Target
}
df = pd.DataFrame(data)

df.head()

     Room_Type Object_Color Object_Size Target_Object
0      Kitchen          Red       Small           Cup
1      Bedroom         Blue       Large           Bed
2  Living Room        Green      Medium          Sofa
3      Kitchen          Red      Medium         Plate
4      Bedroom         Blue       Small         Chair

In [15]:
# dataset that we can encode only these two features
df[['Room_Type', 'Object_Color']].head()

     Room_Type Object_Color
0      Kitchen          Red
1      Bedroom         Blue
2  Living Room        Green
3      Kitchen          Red
4      Bedroom         Blue

In [13]:
df['Room_Type'].value_counts()

Room_Type
Kitchen        2
Bedroom        2
Living Room    1
Name: count, dtype: int64

In [14]:
df['Object_Color'].value_counts()

Object_Color
Red      2
Blue     2
Green    1
Name: count, dtype: int64

In [22]:
# Initialize OneHotEncoder
ohe = OneHotEncoder(sparse_output = False, drop = 'first')

# fit and transform nominal columns
nominal_features = df[['Room_Type', 'Object_Color']]
encoded_nominal = ohe.fit_transform(nominal_features)

# convert back to df for viewing
encoded_column = ohe.get_feature_names_out(['Room_Type', 'Object_Color'])
df_nominal_encoded = pd.DataFrame(encoded_nominal , columns = encoded_columns)
df_nominal_encoded

,Room_Type_Kitchen,Room_Type_Living Room,Object_Color_Green,Object_Color_Red
0,1.0,0.0,0.0,1.0
1,0.0,0.0,0.0,0.0
2,0.0,1.0,1.0,0.0
3,1.0,0.0,0.0,1.0
4,0.0,0.0,0.0,0.0

In [19]:
encoded_columns

array(['Room_Type_Kitchen', 'Room_Type_Living Room', 'Object_Color_Green',
       'Object_Color_Red'], dtype=object)

## Nominal Encoding:

In [37]:
from sklearn.preprocessing import OrdinalEncoder
df

     Room_Type Object_Color Object_Size Target_Object  Object_Size_Encoded
0      Kitchen          Red       Small           Cup                  0.0
1      Bedroom         Blue       Large           Bed                  2.0
2  Living Room        Green      Medium          Sofa                  1.0
3      Kitchen          Red      Medium         Plate                  1.0
4      Bedroom         Blue       Small         Chair                  0.0

In [38]:
df['Object_Size'].value_counts()

Object_Size
Small     2
Medium    2
Large     1
Name: count, dtype: int64

In [44]:
# I just encode one object-size column in nominal encoding because it has sequence or size 

# first define order
size_ord = [['Small', 'Medium', 'Large']]

# initialize encoder for specific categories
ord_encoder = OrdinalEncoder(categories = size_ord)

# Fit and Transform Ordinal column
df['Object_Size_Encoded'] = ord_encoder.fit_transform(df[['Object_Size']])
df[['Object_Size','Object_Size_Encoded']]

  Object_Size  Object_Size_Encoded
0       Small                  0.0
1       Large                  2.0
2      Medium                  1.0
3      Medium                  1.0
4       Small                  0.0

## ColumnTransformer & Pipeline:
- In industry level development we don't use separatly ordinal or nomincal encoding.
- We use ColumnTransformer and Pipeline to make code error free and deployable

In [47]:
# importing import module for transformer and pipeline
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

In [1]:
import datetime
today = datetime.date.today()
print("Today's date:", today)

Today's date: 2026-03-11